version: '3'
services: 
  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
    links:
      - redis
  redis:
    image: redis
    expose:
      - "6379"
    sysctls:
      net.core.somaxconn: 65535
